import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillTwitterCircle,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nina Wolfs Prortofolio</title>
        <meta name="description" content="Generated by Nina Wolfs" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          {/* Navbar */}
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Developed by NinaW.</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/* Frontpage */}
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Nina Wolfs
            </h2>
            <h3 className="text-2xl py-2">Front-end Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              Hi there! I'm a passionate front-end developer with a keen eye for
              design and a hunger to learn. I have experience building
              responsive and user-friendly websites using HTML, CSS, JavaScript,
              React JS, Tailwind and may more! I'm always looking for new
              challenges to improve my skills. I'm comfortable working with
              modern web development tools such as React, Bootstrap, and Git,
              and I'm always eager to learn more. I believe that great design
              and intuitive user experience are essential components of any
              successful website, and I strive to create websites that are both
              visually appealing and functional. If you're looking for a
              front-end developer who is passionate, driven, and eager to learn,
              I'd love to chat and see how we can work together.
            </p>
          </div>

          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillGithub />
            <AiFillLinkedin />
            <AiFillTwitterCircle />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>

        {/*Secondpage */}
        <section>
          <div>
            <h3 className="text-3xl py-1">what I have to offer</h3>
            <p>
              As a beginning front-end developer, I offer a range of services to
              help businesses and individuals build and improve their online
              presence. These services include:
              <ul>
                <li>
                  Website design and development: I can help you create a custom
                  website that meets your specific needs, whether you're looking
                  for a simple landing page or a complex web application.
                </li>
                <li>
                  Responsive design: I can ensure that your website is optimized
                  for different devices and screen sizes, providing a seamless
                  user experience for your visitors.
                </li>
                <li>
                  Website maintenance and updates: I can help you keep your
                  website up to date with the latest content, features, and
                  security patches, ensuring that it remains fast, reliable, and
                  secure.
                </li>
                <li>
                  Search engine optimization (SEO): I can help you improve your
                  website's visibility and ranking in search engine results,
                  making it easier for potential customers to find you online.
                </li>
                <li>
                  User experience (UX) design: I can help you create a website
                  that is intuitive and easy to use, ensuring that your visitors
                  have a positive experience and are more likely to engage with
                  your content.
                </li>
              </ul>
              Whether you're a small business looking to establish an online
              presence, a blogger wanting to start a new website, or a larger
              organization looking to improve your existing website, I can help.
              Let's work together to build a website that meets your needs and
              exceeds your expectations.
            </p>
          </div>
        </section>
      </main>
    </div>
  );
}
